// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"x-admin/internal/dao/internal"
)

// sysAdminDao is the data access object for the table sys_admin.
// You can define custom methods on it to extend its functionality as needed.
type sysAdminDao struct {
	*internal.SysAdminDao
}

var (
	// SysAdmin is a globally accessible object for table sys_admin operations.
	SysAdmin = sysAdminDao{internal.NewSysAdminDao()}
)

// Add your custom methods and functionality below.
